# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6d0fb5360a57bef25a6c2eb4af85207dcbd22d4fef976215130c5600a20223704657395ed09dd6800dbfb67ec5b51b0da6f79e462445e56d9ee51ff46a950e

test:
  secret_key_base: 3626fee703bc8bf38f631582720ef96aa3a89b2345cce762e92c6975f550287a6ba2a869a484841d172883542ad3932b1172348686a3394930899f64b5d4453f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
